#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")"

mkdir -p output

modelsize=1M

fasttext supervised                         \
         -label "__label__"                 \
         -lr 0.1                            \
         -dim 100                           \
         -ws 5                              \
         -wordNgrams 1                      \
         -minn 2                            \
         -maxn 5                            \
         -input corpus/train                \
         -output output/"${modelsize}"model \
         -autotune-validation corpus/valid  \
         -autotune-modelsize "${modelsize}" \
         -autotune-duration 600

echo hvad er dette | fasttext predict-prob output/"${modelsize}"model.ftz - 3
echo hva  er dette | fasttext predict-prob output/"${modelsize}"model.ftz - 3
echo kva  er dette | fasttext predict-prob output/"${modelsize}"model.ftz - 3
