PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE languageNames (id integer primary key, lg text, inLg text, name text, unique(lg, inLg) on conflict replace);
INSERT INTO "languageNames" VALUES(113,'sah','af','Аппырыкааныстыы');
INSERT INTO "languageNames" VALUES(114,'sah','ar','Араабтыы');
INSERT INTO "languageNames" VALUES(115,'sah','az','Адьырбайдьаанныы');
INSERT INTO "languageNames" VALUES(116,'sah','be','Бөлөрүүстүү');
INSERT INTO "languageNames" VALUES(117,'sah','bg','Булҕаардыы');
INSERT INTO "languageNames" VALUES(118,'sah','bn','Бенгаллыы');
INSERT INTO "languageNames" VALUES(119,'sah','ca','Каталаанныы');
INSERT INTO "languageNames" VALUES(120,'sah','cs','Чиэскэйдии');
INSERT INTO "languageNames" VALUES(121,'sah','da','Даатскайдыы');
INSERT INTO "languageNames" VALUES(122,'sah','de','Ниэмэстии');
INSERT INTO "languageNames" VALUES(123,'sah','el','Гириэктии');
INSERT INTO "languageNames" VALUES(124,'sah','en','Аҥылычаанныы');
INSERT INTO "languageNames" VALUES(125,'sah','es','Ыспаанныы');
INSERT INTO "languageNames" VALUES(126,'sah','et','Эстиэнийэлии');
INSERT INTO "languageNames" VALUES(127,'sah','fa','Пиэрсийэлии');
INSERT INTO "languageNames" VALUES(128,'sah','fi','Пииннии');
INSERT INTO "languageNames" VALUES(129,'sah','fr','Пырансуустуу');
INSERT INTO "languageNames" VALUES(130,'sah','hu','Бэҥгиэрдии');
INSERT INTO "languageNames" VALUES(131,'sah','hy','Эрмээннии');
INSERT INTO "languageNames" VALUES(132,'sah','it','Ытаалыйалыы');
INSERT INTO "languageNames" VALUES(133,'sah','kk','Хаһаахтыы');
INSERT INTO "languageNames" VALUES(134,'sah','ko','Кэриэйдии');
INSERT INTO "languageNames" VALUES(135,'sah','ky','Кыргыстыы');
INSERT INTO "languageNames" VALUES(136,'sah','la','Латыынныы');
INSERT INTO "languageNames" VALUES(137,'sah','ne','Ньыпааллыы');
INSERT INTO "languageNames" VALUES(138,'sah','pa','Пандьаабтыы');
INSERT INTO "languageNames" VALUES(139,'sah','pt','Португааллыы');
INSERT INTO "languageNames" VALUES(140,'sah','ro','Румыынныы');
INSERT INTO "languageNames" VALUES(141,'sah','ru','Нууччалыы');
INSERT INTO "languageNames" VALUES(142,'sah','sk','Словаактыы');
INSERT INTO "languageNames" VALUES(143,'sah','sq','Албаанскайдыы');
INSERT INTO "languageNames" VALUES(144,'sah','te','Төлүгүлүү');
INSERT INTO "languageNames" VALUES(145,'sah','tg','Тадьыыктыы');
INSERT INTO "languageNames" VALUES(146,'sah','uk','Украйыыньыстыы');
INSERT INTO "languageNames" VALUES(147,'sah','uz','Үзбиэктии');
INSERT INTO "languageNames" VALUES(148,'sah','zh','Кытайдыы');
INSERT INTO "languageNames" VALUES(149,'sah','zu','Зуулулуу');
INSERT INTO "languageNames" VALUES(150,'ky','af','африкаанча');
INSERT INTO "languageNames" VALUES(151,'ky','ar','арабча');
INSERT INTO "languageNames" VALUES(152,'ky','as','ассамча');
INSERT INTO "languageNames" VALUES(153,'ky','az','азербайжанча');
INSERT INTO "languageNames" VALUES(99001,'ky','ba','башкортчо');
INSERT INTO "languageNames" VALUES(154,'ky','be','беларусча');
INSERT INTO "languageNames" VALUES(155,'ky','bg','болгарияча');
INSERT INTO "languageNames" VALUES(156,'ky','bn','бангладешче');
INSERT INTO "languageNames" VALUES(157,'ky','br','бретон');
INSERT INTO "languageNames" VALUES(158,'ky','ca','каталанча');
INSERT INTO "languageNames" VALUES(159,'ky','cs','чех тили');
INSERT INTO "languageNames" VALUES(160,'ky','cy','уелшче');
INSERT INTO "languageNames" VALUES(161,'ky','da','датча');
INSERT INTO "languageNames" VALUES(162,'ky','de','немисче');
INSERT INTO "languageNames" VALUES(163,'ky','el','грекче');
INSERT INTO "languageNames" VALUES(164,'ky','en','англисче');
INSERT INTO "languageNames" VALUES(165,'ky','eo','эсперанто');
INSERT INTO "languageNames" VALUES(166,'ky','es','испанча');
INSERT INTO "languageNames" VALUES(167,'ky','et','эстончо');
INSERT INTO "languageNames" VALUES(168,'ky','eu','баскча');
INSERT INTO "languageNames" VALUES(169,'ky','fa','Фарзча');
INSERT INTO "languageNames" VALUES(170,'ky','fi','финче');
INSERT INTO "languageNames" VALUES(171,'ky','fo','фароэче');
INSERT INTO "languageNames" VALUES(172,'ky','fr','французча');
INSERT INTO "languageNames" VALUES(173,'ky','fy','батыш фризче');
INSERT INTO "languageNames" VALUES(174,'ky','ga','ирландча');
INSERT INTO "languageNames" VALUES(175,'ky','gn','гуараш');
INSERT INTO "languageNames" VALUES(176,'ky','he','ивритче');
INSERT INTO "languageNames" VALUES(177,'ky','hi','индусча');
INSERT INTO "languageNames" VALUES(178,'ky','ht','гаитиче');
INSERT INTO "languageNames" VALUES(179,'ky','hu','венгрияча');
INSERT INTO "languageNames" VALUES(180,'ky','hy','армянча');
INSERT INTO "languageNames" VALUES(181,'ky','id','индонезияча');
INSERT INTO "languageNames" VALUES(182,'ky','is','исландча');
INSERT INTO "languageNames" VALUES(183,'ky','it','италиянча');
INSERT INTO "languageNames" VALUES(184,'ky','kk','казакча');
INSERT INTO "languageNames" VALUES(185,'ky','ko','корейче');
INSERT INTO "languageNames" VALUES(186,'ky','ku','куртча');
INSERT INTO "languageNames" VALUES(99002,'ky','kum','кумукча');
INSERT INTO "languageNames" VALUES(187,'ky','ky','кыргызча');
INSERT INTO "languageNames" VALUES(188,'ky','la','латынча');
INSERT INTO "languageNames" VALUES(189,'ky','lb','Люксембургча');
INSERT INTO "languageNames" VALUES(190,'ky','lo','лаочо');
INSERT INTO "languageNames" VALUES(191,'ky','lt','литвача');
INSERT INTO "languageNames" VALUES(192,'ky','lv','латвияча');
INSERT INTO "languageNames" VALUES(193,'ky','mk','македонияча');
INSERT INTO "languageNames" VALUES(194,'ky','ml','малайаламча');
INSERT INTO "languageNames" VALUES(195,'ky','mr','маратиче');
INSERT INTO "languageNames" VALUES(196,'ky','mt','малтизче');
INSERT INTO "languageNames" VALUES(197,'ky','nb','норвежче букмалча');
INSERT INTO "languageNames" VALUES(198,'ky','ne','непалча');
INSERT INTO "languageNames" VALUES(199,'ky','nl','голландча');
INSERT INTO "languageNames" VALUES(200,'ky','nn','норвегияча');
INSERT INTO "languageNames" VALUES(201,'ky','no','норвежче');
INSERT INTO "languageNames" VALUES(202,'ky','pa','пунжабиче');
INSERT INTO "languageNames" VALUES(203,'ky','pl','полякча');
INSERT INTO "languageNames" VALUES(204,'ky','pt','португалча');
INSERT INTO "languageNames" VALUES(205,'ky','rm','романшча');
INSERT INTO "languageNames" VALUES(206,'ky','ro','румынияча');
INSERT INTO "languageNames" VALUES(207,'ky','ru','орусча');
INSERT INTO "languageNames" VALUES(208,'ky','sa','санскритче');
INSERT INTO "languageNames" VALUES(209,'ky','sh','серб-хорват');
INSERT INTO "languageNames" VALUES(210,'ky','si','сингалача');
INSERT INTO "languageNames" VALUES(211,'ky','sk','словакча');
INSERT INTO "languageNames" VALUES(212,'ky','sl','словенче');
INSERT INTO "languageNames" VALUES(213,'ky','sq','албанча');
INSERT INTO "languageNames" VALUES(214,'ky','sv','шведче');
INSERT INTO "languageNames" VALUES(215,'ky','sw','суахиличе');
INSERT INTO "languageNames" VALUES(216,'ky','te','телугуча');
INSERT INTO "languageNames" VALUES(217,'ky','tg','тажикче');
INSERT INTO "languageNames" VALUES(218,'ky','th','тайча');
INSERT INTO "languageNames" VALUES(219,'ky','tk','түркмөнчө');
INSERT INTO "languageNames" VALUES(220,'ky','tr','түркчө');
INSERT INTO "languageNames" VALUES(221,'ky','tt','татарча');
INSERT INTO "languageNames" VALUES(222,'ky','uk','украинче');
INSERT INTO "languageNames" VALUES(223,'ky','ur','урдуча');
INSERT INTO "languageNames" VALUES(224,'ky','uz','өзбекче');
INSERT INTO "languageNames" VALUES(225,'ky','vi','вьетнамча');
INSERT INTO "languageNames" VALUES(226,'ky','xh','косача');
INSERT INTO "languageNames" VALUES(227,'ky','zh','кытайча');
INSERT INTO "languageNames" VALUES(228,'ky','zu','зулуча');
INSERT INTO "languageNames" VALUES(229,'kk','af','африкаанс');
INSERT INTO "languageNames" VALUES(230,'kk','ar','араб');
INSERT INTO "languageNames" VALUES(231,'kk','as','ассам');
INSERT INTO "languageNames" VALUES(232,'kk','az','әзірбайжан тілі');
INSERT INTO "languageNames" VALUES(99003,'kk','ba','башқортша');
INSERT INTO "languageNames" VALUES(233,'kk','be','беларус');
INSERT INTO "languageNames" VALUES(234,'kk','bg','болгар');
INSERT INTO "languageNames" VALUES(235,'kk','bn','бенгал');
INSERT INTO "languageNames" VALUES(236,'kk','br','брит');
INSERT INTO "languageNames" VALUES(237,'kk','ca','каталан');
INSERT INTO "languageNames" VALUES(238,'kk','cs','чех');
INSERT INTO "languageNames" VALUES(239,'kk','cy','валлий');
INSERT INTO "languageNames" VALUES(240,'kk','da','дат');
INSERT INTO "languageNames" VALUES(241,'kk','de','неміс тілі');
INSERT INTO "languageNames" VALUES(242,'kk','el','грек');
INSERT INTO "languageNames" VALUES(243,'kk','en','ағылшынша');
INSERT INTO "languageNames" VALUES(244,'kk','eo','эсперанто');
INSERT INTO "languageNames" VALUES(245,'kk','es','испан тілі');
INSERT INTO "languageNames" VALUES(246,'kk','et','эстон');
INSERT INTO "languageNames" VALUES(247,'kk','eu','баск');
INSERT INTO "languageNames" VALUES(248,'kk','fa','парсы');
INSERT INTO "languageNames" VALUES(249,'kk','fi','фин');
INSERT INTO "languageNames" VALUES(250,'kk','fo','фарер');
INSERT INTO "languageNames" VALUES(251,'kk','fr','француз тілі');
INSERT INTO "languageNames" VALUES(252,'kk','fy','батыс фриз');
INSERT INTO "languageNames" VALUES(253,'kk','ga','ирланд');
INSERT INTO "languageNames" VALUES(254,'kk','gd','шотландиялық гэл тілі');
INSERT INTO "languageNames" VALUES(255,'kk','gn','гуарани');
INSERT INTO "languageNames" VALUES(256,'kk','he','иврит');
INSERT INTO "languageNames" VALUES(257,'kk','hi','хинди');
INSERT INTO "languageNames" VALUES(258,'kk','ht','гаитян');
INSERT INTO "languageNames" VALUES(259,'kk','hu','венгер');
INSERT INTO "languageNames" VALUES(260,'kk','hy','армян');
INSERT INTO "languageNames" VALUES(261,'kk','ia','интерлингва');
INSERT INTO "languageNames" VALUES(262,'kk','id','индонезия');
INSERT INTO "languageNames" VALUES(263,'kk','is','исланд');
INSERT INTO "languageNames" VALUES(264,'kk','it','итальян тілі');
INSERT INTO "languageNames" VALUES(265,'kk','kk','қазақша');
INSERT INTO "languageNames" VALUES(266,'kk','ko','кәріс');
INSERT INTO "languageNames" VALUES(267,'kk','ku','күрд');
INSERT INTO "languageNames" VALUES(99004,'kk','kum','құмықша');
INSERT INTO "languageNames" VALUES(268,'kk','ky','қырғызша');
INSERT INTO "languageNames" VALUES(269,'kk','la','латын');
INSERT INTO "languageNames" VALUES(270,'kk','lb','люксембург');
INSERT INTO "languageNames" VALUES(271,'kk','lo','лаос');
INSERT INTO "languageNames" VALUES(272,'kk','lt','литва');
INSERT INTO "languageNames" VALUES(273,'kk','lv','латыш');
INSERT INTO "languageNames" VALUES(274,'kk','mk','македон');
INSERT INTO "languageNames" VALUES(275,'kk','ml','малайялам');
INSERT INTO "languageNames" VALUES(276,'kk','mr','маратхи');
INSERT INTO "languageNames" VALUES(277,'kk','mt','мальта');
INSERT INTO "languageNames" VALUES(278,'kk','nb','норвегиялық букмол');
INSERT INTO "languageNames" VALUES(279,'kk','ne','непал');
INSERT INTO "languageNames" VALUES(280,'kk','nl','голланд');
INSERT INTO "languageNames" VALUES(281,'kk','nn','норвегиялық нинорск');
INSERT INTO "languageNames" VALUES(282,'kk','no','норвег');
INSERT INTO "languageNames" VALUES(283,'kk','oc','окситан');
INSERT INTO "languageNames" VALUES(284,'kk','os','осетин');
INSERT INTO "languageNames" VALUES(285,'kk','pa','панджаб');
INSERT INTO "languageNames" VALUES(286,'kk','pl','поляк');
INSERT INTO "languageNames" VALUES(287,'kk','pt','португал тілі');
INSERT INTO "languageNames" VALUES(288,'kk','rm','романш');
INSERT INTO "languageNames" VALUES(289,'kk','rn','рунди');
INSERT INTO "languageNames" VALUES(290,'kk','ro','румын');
INSERT INTO "languageNames" VALUES(291,'kk','ru','орыс тілі');
INSERT INTO "languageNames" VALUES(292,'kk','sa','санскрит');
INSERT INTO "languageNames" VALUES(293,'kk','se','Солтүстік саам');
INSERT INTO "languageNames" VALUES(294,'kk','sh','сербхорват');
INSERT INTO "languageNames" VALUES(295,'kk','si','сингал');
INSERT INTO "languageNames" VALUES(296,'kk','sk','словак');
INSERT INTO "languageNames" VALUES(297,'kk','sl','словен');
INSERT INTO "languageNames" VALUES(298,'kk','sq','албан');
INSERT INTO "languageNames" VALUES(299,'kk','sv','швед');
INSERT INTO "languageNames" VALUES(300,'kk','sw','суахили');
INSERT INTO "languageNames" VALUES(301,'kk','te','телугу');
INSERT INTO "languageNames" VALUES(302,'kk','tg','тәжік');
INSERT INTO "languageNames" VALUES(303,'kk','th','тай');
INSERT INTO "languageNames" VALUES(304,'kk','tk','түрікменше');
INSERT INTO "languageNames" VALUES(305,'kk','tr','түрікше');
INSERT INTO "languageNames" VALUES(306,'kk','tt','татарша');
INSERT INTO "languageNames" VALUES(307,'kk','uk','украин');
INSERT INTO "languageNames" VALUES(308,'kk','ur','урду');
INSERT INTO "languageNames" VALUES(309,'kk','uz','өзбекше');
INSERT INTO "languageNames" VALUES(310,'kk','vi','вьетнам');
INSERT INTO "languageNames" VALUES(311,'kk','xh','ксоза');
INSERT INTO "languageNames" VALUES(312,'kk','zh','қытай тілі');
INSERT INTO "languageNames" VALUES(313,'kk','zu','зулу');
INSERT INTO "languageNames" VALUES(314,'tr','af','Afrikaanca');
INSERT INTO "languageNames" VALUES(315,'tr','ar','Arapça');
INSERT INTO "languageNames" VALUES(316,'tr','as','Assamca');
INSERT INTO "languageNames" VALUES(317,'tr','av','Avar Dili');
INSERT INTO "languageNames" VALUES(319,'tr','az','Azerice');
INSERT INTO "languageNames" VALUES(320,'tr','ba','Başkırtça');
INSERT INTO "languageNames" VALUES(321,'tr','be','Beyaz Rusça');
INSERT INTO "languageNames" VALUES(322,'tr','bg','Bulgarca');
INSERT INTO "languageNames" VALUES(323,'tr','bi','Bislama');
INSERT INTO "languageNames" VALUES(324,'tr','bn','Bengalce');
INSERT INTO "languageNames" VALUES(325,'tr','br','Breton');
INSERT INTO "languageNames" VALUES(326,'tr','bua','Buryat');
INSERT INTO "languageNames" VALUES(327,'tr','ca','Katalanca');
INSERT INTO "languageNames" VALUES(328,'tr','ceb','Cebuano');
INSERT INTO "languageNames" VALUES(329,'tr','ckb','Orta Kürtçe');
INSERT INTO "languageNames" VALUES(330,'tr','co','Korsikaca');
INSERT INTO "languageNames" VALUES(331,'tr','cs','Çekçe');
INSERT INTO "languageNames" VALUES(332,'tr','csb','Kashubian');
INSERT INTO "languageNames" VALUES(333,'tr','cu','Kilise Slavcası');
INSERT INTO "languageNames" VALUES(334,'tr','cv','Çuvaşça');
INSERT INTO "languageNames" VALUES(335,'tr','cy','Galce');
INSERT INTO "languageNames" VALUES(336,'tr','da','Danca');
INSERT INTO "languageNames" VALUES(337,'tr','de','Almanca');
INSERT INTO "languageNames" VALUES(338,'tr','dsb','Aşağı Sorbça');
INSERT INTO "languageNames" VALUES(339,'tr','el','Yunanca');
INSERT INTO "languageNames" VALUES(340,'tr','en','İngilizce');
INSERT INTO "languageNames" VALUES(341,'tr','eo','Esperanto');
INSERT INTO "languageNames" VALUES(342,'tr','es','İspanyolca');
INSERT INTO "languageNames" VALUES(343,'tr','et','Estonca');
INSERT INTO "languageNames" VALUES(344,'tr','eu','Baskça');
INSERT INTO "languageNames" VALUES(345,'tr','fa','Farsça');
INSERT INTO "languageNames" VALUES(346,'tr','fi','Fince');
INSERT INTO "languageNames" VALUES(347,'tr','fo','Faroe Dili');
INSERT INTO "languageNames" VALUES(348,'tr','fr','Fransızca');
INSERT INTO "languageNames" VALUES(349,'tr','fy','Batı Frizcesi');
INSERT INTO "languageNames" VALUES(350,'tr','ga','İrlandaca');
INSERT INTO "languageNames" VALUES(351,'tr','gd','İskoç Gal Dili');
INSERT INTO "languageNames" VALUES(352,'tr','gn','Guarani Dili');
INSERT INTO "languageNames" VALUES(353,'tr','gv','Manks');
INSERT INTO "languageNames" VALUES(354,'tr','he','İbranice');
INSERT INTO "languageNames" VALUES(355,'tr','hi','Hintçe');
INSERT INTO "languageNames" VALUES(356,'tr','hsb','Yukarı Sorbça');
INSERT INTO "languageNames" VALUES(357,'tr','ht','Haiti Dili');
INSERT INTO "languageNames" VALUES(358,'tr','hu','Macarca');
INSERT INTO "languageNames" VALUES(359,'tr','hy','Ermenice');
INSERT INTO "languageNames" VALUES(360,'tr','ia','Interlingua');
INSERT INTO "languageNames" VALUES(361,'tr','id','Endonezce');
INSERT INTO "languageNames" VALUES(362,'tr','is','İzlandaca');
INSERT INTO "languageNames" VALUES(363,'tr','it','İtalyanca');
INSERT INTO "languageNames" VALUES(364,'tr','kaa','Karakalpakça');
INSERT INTO "languageNames" VALUES(365,'tr','kk','Kazakça');
INSERT INTO "languageNames" VALUES(366,'tr','ko','Korece');
INSERT INTO "languageNames" VALUES(367,'tr','ku','Kürtçe');
INSERT INTO "languageNames" VALUES(368,'tr','kum','Kumukça');
INSERT INTO "languageNames" VALUES(369,'tr','kv','Komi');
INSERT INTO "languageNames" VALUES(370,'tr','ky','Kırgızca');
INSERT INTO "languageNames" VALUES(371,'tr','la','Latince');
INSERT INTO "languageNames" VALUES(372,'tr','lb','Lüksemburgca');
INSERT INTO "languageNames" VALUES(373,'tr','lg','Ganda');
INSERT INTO "languageNames" VALUES(374,'tr','lo','Laoca');
INSERT INTO "languageNames" VALUES(375,'tr','lt','Litvanyaca');
INSERT INTO "languageNames" VALUES(376,'tr','lv','Letonca');
INSERT INTO "languageNames" VALUES(377,'tr','mfe','Morisyen');
INSERT INTO "languageNames" VALUES(378,'tr','mk','Makedonca');
INSERT INTO "languageNames" VALUES(379,'tr','ml','Malayalam');
INSERT INTO "languageNames" VALUES(380,'tr','mr','Marathi');
INSERT INTO "languageNames" VALUES(381,'tr','mt','Maltaca');
INSERT INTO "languageNames" VALUES(382,'tr','myv','Erzya');
INSERT INTO "languageNames" VALUES(383,'tr','nb','Norveççe Bokmål');
INSERT INTO "languageNames" VALUES(384,'tr','ne','Nepalce');
INSERT INTO "languageNames" VALUES(385,'tr','nl','Hollandaca');
INSERT INTO "languageNames" VALUES(386,'tr','nn','Norveççe Nynorsk');
INSERT INTO "languageNames" VALUES(387,'tr','no','Norveççe');
INSERT INTO "languageNames" VALUES(388,'tr','nog','Nogayca');
INSERT INTO "languageNames" VALUES(389,'tr','oc','Occitan');
INSERT INTO "languageNames" VALUES(390,'tr','os','Osetçe');
INSERT INTO "languageNames" VALUES(391,'tr','pa','Pencapça');
INSERT INTO "languageNames" VALUES(392,'tr','pl','Lehçe');
INSERT INTO "languageNames" VALUES(393,'tr','pt','Portekizce');
INSERT INTO "languageNames" VALUES(394,'tr','rm','Romanşça');
INSERT INTO "languageNames" VALUES(395,'tr','rn','Kirundi');
INSERT INTO "languageNames" VALUES(396,'tr','ro','Romence');
INSERT INTO "languageNames" VALUES(397,'tr','ru','Rusça');
INSERT INTO "languageNames" VALUES(398,'tr','rup','Ulahça');
INSERT INTO "languageNames" VALUES(399,'tr','sa','Sanskritçe');
INSERT INTO "languageNames" VALUES(400,'tr','sc','Sardunya Dili');
INSERT INTO "languageNames" VALUES(401,'tr','sco','Scots');
INSERT INTO "languageNames" VALUES(402,'tr','se','Kuzey Sami');
INSERT INTO "languageNames" VALUES(403,'tr','sh','Sırp-Hırvat Dili');
INSERT INTO "languageNames" VALUES(404,'tr','si','Seylanca');
INSERT INTO "languageNames" VALUES(405,'tr','sk','Slovakça');
INSERT INTO "languageNames" VALUES(406,'tr','sl','Slovence');
INSERT INTO "languageNames" VALUES(407,'tr','sma','Güney Sami');
INSERT INTO "languageNames" VALUES(408,'tr','smj','Lule Sami');
INSERT INTO "languageNames" VALUES(409,'tr','sq','Arnavutça');
INSERT INTO "languageNames" VALUES(410,'tr','sv','İsveççe');
INSERT INTO "languageNames" VALUES(411,'tr','sw','Svahili');
INSERT INTO "languageNames" VALUES(412,'tr','te','Telugu Dili');
INSERT INTO "languageNames" VALUES(413,'tr','tet','Tetum');
INSERT INTO "languageNames" VALUES(414,'tr','tg','Tacikçe');
INSERT INTO "languageNames" VALUES(415,'tr','th','Tayca');
INSERT INTO "languageNames" VALUES(416,'tr','tk','Türkmence');
INSERT INTO "languageNames" VALUES(417,'tr','tl','Takalotça');
INSERT INTO "languageNames" VALUES(418,'tr','tr','Türkçe');
INSERT INTO "languageNames" VALUES(419,'tr','tt','Tatarca');
INSERT INTO "languageNames" VALUES(420,'tr','tyv','Tuvaca');
INSERT INTO "languageNames" VALUES(421,'tr','udm','Udmurtça');
INSERT INTO "languageNames" VALUES(422,'tr','uk','Ukraynaca');
INSERT INTO "languageNames" VALUES(423,'tr','ur','Urduca');
INSERT INTO "languageNames" VALUES(424,'tr','uz','Özbekçe');
INSERT INTO "languageNames" VALUES(425,'tr','vi','Vietnamca');
INSERT INTO "languageNames" VALUES(426,'tr','xh','Zosa');
INSERT INTO "languageNames" VALUES(427,'tr','zh','Çince');
INSERT INTO "languageNames" VALUES(428,'tr','zu','Zuluca');
INSERT INTO "languageNames" VALUES(429,'uz','af','afrikancha');
INSERT INTO "languageNames" VALUES(430,'uz','ar','arabcha');
INSERT INTO "languageNames" VALUES(431,'uz','as','assamcha');
INSERT INTO "languageNames" VALUES(432,'uz','az','ozarbayjoncha');
INSERT INTO "languageNames" VALUES(433,'uz','be','belaruscha');
INSERT INTO "languageNames" VALUES(434,'uz','bg','bolgarcha');
INSERT INTO "languageNames" VALUES(435,'uz','bn','bengalcha');
INSERT INTO "languageNames" VALUES(436,'uz','ca','katalancha');
INSERT INTO "languageNames" VALUES(437,'uz','cs','chexcha');
INSERT INTO "languageNames" VALUES(438,'uz','cy','uelscha');
INSERT INTO "languageNames" VALUES(439,'uz','da','daniyacha');
INSERT INTO "languageNames" VALUES(440,'uz','de','olmoncha');
INSERT INTO "languageNames" VALUES(441,'uz','el','grekcha');
INSERT INTO "languageNames" VALUES(442,'uz','en','inglizcha');
INSERT INTO "languageNames" VALUES(443,'uz','eo','esperanto');
INSERT INTO "languageNames" VALUES(444,'uz','es','ispancha');
INSERT INTO "languageNames" VALUES(445,'uz','et','estoncha');
INSERT INTO "languageNames" VALUES(446,'uz','eu','baskcha');
INSERT INTO "languageNames" VALUES(447,'uz','fa','forscha');
INSERT INTO "languageNames" VALUES(448,'uz','fi','fincha');
INSERT INTO "languageNames" VALUES(449,'uz','fo','farercha');
INSERT INTO "languageNames" VALUES(450,'uz','fr','fransuzcha');
INSERT INTO "languageNames" VALUES(451,'uz','fy','gʻarbiy friziancha');
INSERT INTO "languageNames" VALUES(452,'uz','ga','irlandcha');
INSERT INTO "languageNames" VALUES(453,'uz','gn','guarani');
INSERT INTO "languageNames" VALUES(454,'uz','he','ibroniy');
INSERT INTO "languageNames" VALUES(455,'uz','hi','hindcha');
INSERT INTO "languageNames" VALUES(456,'uz','ht','gaitiancha');
INSERT INTO "languageNames" VALUES(457,'uz','hu','vengrcha');
INSERT INTO "languageNames" VALUES(458,'uz','hy','armancha');
INSERT INTO "languageNames" VALUES(459,'uz','id','indoneziyacha');
INSERT INTO "languageNames" VALUES(460,'uz','is','islandcha');
INSERT INTO "languageNames" VALUES(461,'uz','it','italyancha');
INSERT INTO "languageNames" VALUES(462,'uz','kk','qozoqcha');
INSERT INTO "languageNames" VALUES(463,'uz','ko','koreyscha');
INSERT INTO "languageNames" VALUES(464,'uz','ku','kurdcha');
INSERT INTO "languageNames" VALUES(465,'uz','ky','qirgʻizcha');
INSERT INTO "languageNames" VALUES(466,'uz','la','lotincha');
INSERT INTO "languageNames" VALUES(467,'uz','lb','lyuksemburgcha');
INSERT INTO "languageNames" VALUES(468,'uz','lo','lao');
INSERT INTO "languageNames" VALUES(469,'uz','lt','litvacha');
INSERT INTO "languageNames" VALUES(470,'uz','lv','latishcha');
INSERT INTO "languageNames" VALUES(471,'uz','mk','makedoncha');
INSERT INTO "languageNames" VALUES(472,'uz','ml','malayalam');
INSERT INTO "languageNames" VALUES(473,'uz','mr','marati');
INSERT INTO "languageNames" VALUES(474,'uz','mt','maltacha');
INSERT INTO "languageNames" VALUES(475,'uz','nb','norvegcha bokmal');
INSERT INTO "languageNames" VALUES(476,'uz','ne','nepalcha');
INSERT INTO "languageNames" VALUES(477,'uz','nl','gollandcha');
INSERT INTO "languageNames" VALUES(478,'uz','nn','norvegcha ninorsk');
INSERT INTO "languageNames" VALUES(479,'uz','pa','panjobcha');
INSERT INTO "languageNames" VALUES(480,'uz','pl','polyakcha');
INSERT INTO "languageNames" VALUES(481,'uz','pt','portugalcha');
INSERT INTO "languageNames" VALUES(482,'uz','rm','romancha');
INSERT INTO "languageNames" VALUES(483,'uz','ro','rumincha');
INSERT INTO "languageNames" VALUES(484,'uz','ru','ruscha');
INSERT INTO "languageNames" VALUES(485,'uz','sa','sanskritcha');
INSERT INTO "languageNames" VALUES(486,'uz','si','sinxala');
INSERT INTO "languageNames" VALUES(487,'uz','sk','slovakcha');
INSERT INTO "languageNames" VALUES(488,'uz','sl','slovencha');
INSERT INTO "languageNames" VALUES(489,'uz','sq','albancha');
INSERT INTO "languageNames" VALUES(490,'uz','sv','shvedcha');
INSERT INTO "languageNames" VALUES(491,'uz','sw','suaxili');
INSERT INTO "languageNames" VALUES(492,'uz','te','telugu');
INSERT INTO "languageNames" VALUES(493,'uz','tg','tojikcha');
INSERT INTO "languageNames" VALUES(494,'uz','th','taycha');
INSERT INTO "languageNames" VALUES(495,'uz','tk','turkmancha');
INSERT INTO "languageNames" VALUES(496,'uz','tr','turkcha');
INSERT INTO "languageNames" VALUES(497,'uz','tt','tatarcha');
INSERT INTO "languageNames" VALUES(498,'uz','uk','ukraincha');
INSERT INTO "languageNames" VALUES(499,'uz','ur','urdu');
INSERT INTO "languageNames" VALUES(500,'uz','uz','oʻzbekcha');
INSERT INTO "languageNames" VALUES(501,'uz','vi','vyetnamcha');
INSERT INTO "languageNames" VALUES(502,'uz','xh','xosa');
INSERT INTO "languageNames" VALUES(503,'uz','zh','xitoycha');
INSERT INTO "languageNames" VALUES(504,'uz','zu','zulu');
INSERT INTO "languageNames" VALUES(505,'az','af','afrikaans');
INSERT INTO "languageNames" VALUES(506,'az','ar','ərəb');
INSERT INTO "languageNames" VALUES(507,'az','as','assam');
INSERT INTO "languageNames" VALUES(508,'az','av','avarikcə');
INSERT INTO "languageNames" VALUES(509,'az','az','azərbaycan');
INSERT INTO "languageNames" VALUES(510,'az','ba','başkir dili');
INSERT INTO "languageNames" VALUES(511,'az','be','belarus');
INSERT INTO "languageNames" VALUES(512,'az','bg','bolqar');
INSERT INTO "languageNames" VALUES(513,'az','bi','bislama dili');
INSERT INTO "languageNames" VALUES(514,'az','bn','benqal');
INSERT INTO "languageNames" VALUES(515,'az','br','Bretonca');
INSERT INTO "languageNames" VALUES(516,'az','bua','buryat dili');
INSERT INTO "languageNames" VALUES(517,'az','ca','katalan');
INSERT INTO "languageNames" VALUES(518,'az','ceb','kebuano dili');
INSERT INTO "languageNames" VALUES(519,'az','co','korsikan dili');
INSERT INTO "languageNames" VALUES(520,'az','cs','çex');
INSERT INTO "languageNames" VALUES(521,'az','csb','kaşubyan dili');
INSERT INTO "languageNames" VALUES(522,'az','cu','kilsə slav dili');
INSERT INTO "languageNames" VALUES(523,'az','cv','çuvaş dili');
INSERT INTO "languageNames" VALUES(524,'az','cy','uels');
INSERT INTO "languageNames" VALUES(525,'az','da','danimarka');
INSERT INTO "languageNames" VALUES(526,'az','de','alman');
INSERT INTO "languageNames" VALUES(527,'az','dsb','aşağı sorbca');
INSERT INTO "languageNames" VALUES(528,'az','el','yunan');
INSERT INTO "languageNames" VALUES(529,'az','en','ingilis');
INSERT INTO "languageNames" VALUES(530,'az','eo','esperanto');
INSERT INTO "languageNames" VALUES(531,'az','es','ispan');
INSERT INTO "languageNames" VALUES(532,'az','et','eston');
INSERT INTO "languageNames" VALUES(533,'az','eu','bask');
INSERT INTO "languageNames" VALUES(534,'az','fa','fars');
INSERT INTO "languageNames" VALUES(535,'az','fi','fin');
INSERT INTO "languageNames" VALUES(536,'az','fo','farer');
INSERT INTO "languageNames" VALUES(537,'az','fr','fransız');
INSERT INTO "languageNames" VALUES(538,'az','fy','friz');
INSERT INTO "languageNames" VALUES(539,'az','ga','irland');
INSERT INTO "languageNames" VALUES(540,'az','gd','skot gaelik dili');
INSERT INTO "languageNames" VALUES(541,'az','gn','quarani');
INSERT INTO "languageNames" VALUES(542,'az','gv','manks dili');
INSERT INTO "languageNames" VALUES(543,'az','he','ivrit');
INSERT INTO "languageNames" VALUES(544,'az','hi','hindi');
INSERT INTO "languageNames" VALUES(545,'az','hsb','yuxarı sorbca');
INSERT INTO "languageNames" VALUES(546,'az','ht','haiti');
INSERT INTO "languageNames" VALUES(547,'az','hu','macar');
INSERT INTO "languageNames" VALUES(548,'az','hy','erməni');
INSERT INTO "languageNames" VALUES(549,'az','ia','interlingua dili');
INSERT INTO "languageNames" VALUES(550,'az','id','indoneziya');
INSERT INTO "languageNames" VALUES(551,'az','is','island');
INSERT INTO "languageNames" VALUES(552,'az','it','italyan');
INSERT INTO "languageNames" VALUES(553,'az','kaa','qara-qalpaq dili');
INSERT INTO "languageNames" VALUES(554,'az','kk','qazax');
INSERT INTO "languageNames" VALUES(555,'az','ko','koreya');
INSERT INTO "languageNames" VALUES(556,'az','ku','kürd');
INSERT INTO "languageNames" VALUES(557,'az','kum','kumuk dili');
INSERT INTO "languageNames" VALUES(558,'az','kv','komi dili');
INSERT INTO "languageNames" VALUES(559,'az','ky','qırğız');
INSERT INTO "languageNames" VALUES(560,'az','la','latın');
INSERT INTO "languageNames" VALUES(561,'az','lb','lüksemburq');
INSERT INTO "languageNames" VALUES(562,'az','lg','qanda dili');
INSERT INTO "languageNames" VALUES(563,'az','lo','laos');
INSERT INTO "languageNames" VALUES(564,'az','lt','litva');
INSERT INTO "languageNames" VALUES(565,'az','lv','latış');
INSERT INTO "languageNames" VALUES(566,'az','mk','makedon');
INSERT INTO "languageNames" VALUES(567,'az','ml','malayalam');
INSERT INTO "languageNames" VALUES(568,'az','mr','marati');
INSERT INTO "languageNames" VALUES(569,'az','mt','malta');
INSERT INTO "languageNames" VALUES(570,'az','myv','erzya dili');
INSERT INTO "languageNames" VALUES(571,'az','nb','bokmal norveç');
INSERT INTO "languageNames" VALUES(572,'az','ne','nepal');
INSERT INTO "languageNames" VALUES(573,'az','nl','holland');
INSERT INTO "languageNames" VALUES(574,'az','nn','nünorsk norveç');
INSERT INTO "languageNames" VALUES(575,'az','no','norveç dili');
INSERT INTO "languageNames" VALUES(576,'az','nog','noqay dili');
INSERT INTO "languageNames" VALUES(577,'az','oc','oksitanca');
INSERT INTO "languageNames" VALUES(578,'az','os','osetik dili');
INSERT INTO "languageNames" VALUES(579,'az','pa','pəncab');
INSERT INTO "languageNames" VALUES(580,'az','pl','polyak');
INSERT INTO "languageNames" VALUES(581,'az','pt','portuqal');
INSERT INTO "languageNames" VALUES(582,'az','rm','retoroman');
INSERT INTO "languageNames" VALUES(583,'az','rn','rundi dili');
INSERT INTO "languageNames" VALUES(584,'az','ro','rumın');
INSERT INTO "languageNames" VALUES(585,'az','ru','rus');
INSERT INTO "languageNames" VALUES(586,'az','rup','aromanca');
INSERT INTO "languageNames" VALUES(587,'az','sa','sanskrit');
INSERT INTO "languageNames" VALUES(588,'az','sc','sardin dili');
INSERT INTO "languageNames" VALUES(589,'az','sco','skots dili');
INSERT INTO "languageNames" VALUES(590,'az','se','şimal sami dili');
INSERT INTO "languageNames" VALUES(591,'az','sh','serb-xorvatca');
INSERT INTO "languageNames" VALUES(592,'az','si','sinhal');
INSERT INTO "languageNames" VALUES(593,'az','sk','slovak');
INSERT INTO "languageNames" VALUES(594,'az','sl','sloven');
INSERT INTO "languageNames" VALUES(595,'az','sma','cənub sami dili');
INSERT INTO "languageNames" VALUES(596,'az','smj','lule sami dili');
INSERT INTO "languageNames" VALUES(597,'az','sq','alban');
INSERT INTO "languageNames" VALUES(598,'az','sv','isveç');
INSERT INTO "languageNames" VALUES(599,'az','sw','suahili');
INSERT INTO "languageNames" VALUES(600,'az','te','teluqu');
INSERT INTO "languageNames" VALUES(601,'az','tet','tetum dili');
INSERT INTO "languageNames" VALUES(602,'az','tg','tacik');
INSERT INTO "languageNames" VALUES(603,'az','th','tay');
INSERT INTO "languageNames" VALUES(604,'az','tk','türkmən');
INSERT INTO "languageNames" VALUES(605,'az','tl','taqaloq dili');
INSERT INTO "languageNames" VALUES(606,'az','tr','türk');
INSERT INTO "languageNames" VALUES(607,'az','tt','tatar');
INSERT INTO "languageNames" VALUES(608,'az','tyv','tuvinyan dili');
INSERT INTO "languageNames" VALUES(609,'az','udm','udmurt dili');
INSERT INTO "languageNames" VALUES(610,'az','uk','ukrayna');
INSERT INTO "languageNames" VALUES(611,'az','ur','urdu');
INSERT INTO "languageNames" VALUES(612,'az','uz','özbək');
INSERT INTO "languageNames" VALUES(613,'az','vi','vyetnam');
INSERT INTO "languageNames" VALUES(614,'az','xh','xosa');
INSERT INTO "languageNames" VALUES(615,'az','zh','çin');
INSERT INTO "languageNames" VALUES(616,'az','zu','zulu');
INSERT INTO "languageNames" VALUES(617,'ru','af','африкаанс');
INSERT INTO "languageNames" VALUES(618,'ru','ar','арабский');
INSERT INTO "languageNames" VALUES(619,'ru','as','ассамский');
INSERT INTO "languageNames" VALUES(620,'ru','av','аварский');
INSERT INTO "languageNames" VALUES(622,'ru','az','азербайджанский');
INSERT INTO "languageNames" VALUES(623,'ru','ba','башкирский');
INSERT INTO "languageNames" VALUES(624,'ru','be','белорусский');
INSERT INTO "languageNames" VALUES(625,'ru','bg','болгарский');
INSERT INTO "languageNames" VALUES(626,'ru','bi','бислама');
INSERT INTO "languageNames" VALUES(627,'ru','bn','бенгальский');
INSERT INTO "languageNames" VALUES(628,'ru','br','бретонский');
INSERT INTO "languageNames" VALUES(629,'ru','bua','бурятский');
INSERT INTO "languageNames" VALUES(630,'ru','ca','каталанский');
INSERT INTO "languageNames" VALUES(631,'ru','ceb','кебуано');
INSERT INTO "languageNames" VALUES(632,'ru','ckb','сорани курдский');
INSERT INTO "languageNames" VALUES(633,'ru','co','корсиканский');
INSERT INTO "languageNames" VALUES(634,'ru','cs','чешский');
INSERT INTO "languageNames" VALUES(635,'ru','csb','кашубианский');
INSERT INTO "languageNames" VALUES(636,'ru','cu','церковнославянский');
INSERT INTO "languageNames" VALUES(637,'ru','cv','чувашский');
INSERT INTO "languageNames" VALUES(638,'ru','cy','валлийский');
INSERT INTO "languageNames" VALUES(639,'ru','da','датский');
INSERT INTO "languageNames" VALUES(640,'ru','de','немецкий');
INSERT INTO "languageNames" VALUES(641,'ru','dsb','нижнелужицкий');
INSERT INTO "languageNames" VALUES(642,'ru','el','греческий');
INSERT INTO "languageNames" VALUES(643,'ru','en','английский');
INSERT INTO "languageNames" VALUES(644,'ru','eo','эсперанто');
INSERT INTO "languageNames" VALUES(645,'ru','es','испанский');
INSERT INTO "languageNames" VALUES(646,'ru','et','эстонский');
INSERT INTO "languageNames" VALUES(647,'ru','eu','баскский');
INSERT INTO "languageNames" VALUES(648,'ru','fa','персидский');
INSERT INTO "languageNames" VALUES(649,'ru','fi','финский');
INSERT INTO "languageNames" VALUES(650,'ru','fo','фарерский');
INSERT INTO "languageNames" VALUES(651,'ru','fr','французский');
INSERT INTO "languageNames" VALUES(652,'ru','fy','западно-фризский');
INSERT INTO "languageNames" VALUES(653,'ru','ga','ирландский');
INSERT INTO "languageNames" VALUES(654,'ru','gd','гэльский');
INSERT INTO "languageNames" VALUES(655,'ru','gn','гуарани');
INSERT INTO "languageNames" VALUES(656,'ru','gv','мэнский');
INSERT INTO "languageNames" VALUES(657,'ru','he','иврит');
INSERT INTO "languageNames" VALUES(658,'ru','hi','хинди');
INSERT INTO "languageNames" VALUES(659,'ru','hsb','верхнелужицкий');
INSERT INTO "languageNames" VALUES(660,'ru','ht','гаитянский');
INSERT INTO "languageNames" VALUES(661,'ru','hu','венгерский');
INSERT INTO "languageNames" VALUES(662,'ru','hy','армянский');
INSERT INTO "languageNames" VALUES(663,'ru','ia','интерлингва');
INSERT INTO "languageNames" VALUES(664,'ru','id','индонезийский');
INSERT INTO "languageNames" VALUES(665,'ru','is','исландский');
INSERT INTO "languageNames" VALUES(666,'ru','it','итальянский');
INSERT INTO "languageNames" VALUES(667,'ru','kaa','каракалпакский');
INSERT INTO "languageNames" VALUES(668,'ru','kk','казахский');
INSERT INTO "languageNames" VALUES(669,'ru','ko','корейский');
INSERT INTO "languageNames" VALUES(670,'ru','ku','курдский');
INSERT INTO "languageNames" VALUES(671,'ru','kum','кумыкский');
INSERT INTO "languageNames" VALUES(672,'ru','kv','коми');
INSERT INTO "languageNames" VALUES(673,'ru','ky','кыргызский');
INSERT INTO "languageNames" VALUES(674,'ru','la','латинский');
INSERT INTO "languageNames" VALUES(675,'ru','lb','люксембургский');
INSERT INTO "languageNames" VALUES(676,'ru','lg','ганда');
INSERT INTO "languageNames" VALUES(677,'ru','lo','лаосский');
INSERT INTO "languageNames" VALUES(678,'ru','lt','литовский');
INSERT INTO "languageNames" VALUES(679,'ru','lv','латышский');
INSERT INTO "languageNames" VALUES(680,'ru','mfe','маврикийский креольский');
INSERT INTO "languageNames" VALUES(681,'ru','mk','македонский');
INSERT INTO "languageNames" VALUES(682,'ru','ml','малаялам');
INSERT INTO "languageNames" VALUES(683,'ru','mr','маратхи');
INSERT INTO "languageNames" VALUES(684,'ru','mt','мальтийский');
INSERT INTO "languageNames" VALUES(685,'ru','myv','эрзя');
INSERT INTO "languageNames" VALUES(686,'ru','nb','норвежский букмол');
INSERT INTO "languageNames" VALUES(687,'ru','ne','непальский');
INSERT INTO "languageNames" VALUES(688,'ru','nl','голландский');
INSERT INTO "languageNames" VALUES(689,'ru','nn','норвежский нюнорск');
INSERT INTO "languageNames" VALUES(690,'ru','no','норвежский');
INSERT INTO "languageNames" VALUES(691,'ru','nog','ногайский');
INSERT INTO "languageNames" VALUES(692,'ru','oc','окситанский');
INSERT INTO "languageNames" VALUES(693,'ru','os','осетинский');
INSERT INTO "languageNames" VALUES(694,'ru','pa','панджаби');
INSERT INTO "languageNames" VALUES(695,'ru','pl','польский');
INSERT INTO "languageNames" VALUES(696,'ru','pt','португальский');
INSERT INTO "languageNames" VALUES(697,'ru','rm','романшский');
INSERT INTO "languageNames" VALUES(698,'ru','rn','рунди');
INSERT INTO "languageNames" VALUES(699,'ru','ro','румынский');
INSERT INTO "languageNames" VALUES(700,'ru','ru','русский');
INSERT INTO "languageNames" VALUES(701,'ru','rup','арумынский');
INSERT INTO "languageNames" VALUES(702,'ru','sa','санскрит');
INSERT INTO "languageNames" VALUES(703,'ru','sc','сардинский');
INSERT INTO "languageNames" VALUES(704,'ru','sco','шотландский');
INSERT INTO "languageNames" VALUES(705,'ru','se','северносаамский');
INSERT INTO "languageNames" VALUES(706,'ru','sh','сербскохорватский');
INSERT INTO "languageNames" VALUES(707,'ru','si','сингальский');
INSERT INTO "languageNames" VALUES(708,'ru','sk','словацкий');
INSERT INTO "languageNames" VALUES(709,'ru','sl','словенский');
INSERT INTO "languageNames" VALUES(710,'ru','sma','саамский (южный)');
INSERT INTO "languageNames" VALUES(711,'ru','smj','луле-саамский');
INSERT INTO "languageNames" VALUES(712,'ru','sq','албанский');
INSERT INTO "languageNames" VALUES(713,'ru','sv','шведский');
INSERT INTO "languageNames" VALUES(714,'ru','sw','суахили');
INSERT INTO "languageNames" VALUES(715,'ru','te','телугу');
INSERT INTO "languageNames" VALUES(716,'ru','tet','тетум');
INSERT INTO "languageNames" VALUES(717,'ru','tg','таджикский');
INSERT INTO "languageNames" VALUES(718,'ru','th','тайский');
INSERT INTO "languageNames" VALUES(719,'ru','tk','туркменский');
INSERT INTO "languageNames" VALUES(720,'ru','tl','тагалог');
INSERT INTO "languageNames" VALUES(721,'ru','tr','турецкий');
INSERT INTO "languageNames" VALUES(722,'ru','tt','татарский');
INSERT INTO "languageNames" VALUES(723,'ru','tyv','тувинский');
INSERT INTO "languageNames" VALUES(724,'ru','udm','удмуртский');
INSERT INTO "languageNames" VALUES(725,'ru','uk','украинский');
INSERT INTO "languageNames" VALUES(726,'ru','ur','урду');
INSERT INTO "languageNames" VALUES(727,'ru','uz','узбекский');
INSERT INTO "languageNames" VALUES(728,'ru','vi','вьетнамский');
INSERT INTO "languageNames" VALUES(729,'ru','xh','ксоза');
INSERT INTO "languageNames" VALUES(730,'ru','zh','китайский');
INSERT INTO "languageNames" VALUES(731,'ru','zu','зулу');
INSERT INTO "languageNames" VALUES(732,'en','af','Afrikaans');
INSERT INTO "languageNames" VALUES(733,'en','ar','Arabic');
INSERT INTO "languageNames" VALUES(734,'en','as','Assamese');
INSERT INTO "languageNames" VALUES(735,'en','av','Avaric');
INSERT INTO "languageNames" VALUES(737,'en','az','Azeri');
INSERT INTO "languageNames" VALUES(738,'en','ba','Bashkir');
INSERT INTO "languageNames" VALUES(739,'en','be','Belarusian');
INSERT INTO "languageNames" VALUES(740,'en','bg','Bulgarian');
INSERT INTO "languageNames" VALUES(741,'en','bi','Bislama');
INSERT INTO "languageNames" VALUES(742,'en','bn','Bengali');
INSERT INTO "languageNames" VALUES(743,'en','br','Breton');
INSERT INTO "languageNames" VALUES(744,'en','bua','Buriat');
INSERT INTO "languageNames" VALUES(745,'en','ca','Catalan');
INSERT INTO "languageNames" VALUES(746,'en','ceb','Cebuano');
INSERT INTO "languageNames" VALUES(747,'en','ckb','Sorani Kurdish');
INSERT INTO "languageNames" VALUES(748,'en','co','Corsican');
INSERT INTO "languageNames" VALUES(749,'en','cs','Czech');
INSERT INTO "languageNames" VALUES(750,'en','csb','Kashubian');
INSERT INTO "languageNames" VALUES(751,'en','cu','Church Slavic');
INSERT INTO "languageNames" VALUES(752,'en','cv','Chuvash');
INSERT INTO "languageNames" VALUES(753,'en','cy','Welsh');
INSERT INTO "languageNames" VALUES(754,'en','da','Danish');
INSERT INTO "languageNames" VALUES(755,'en','de','German');
INSERT INTO "languageNames" VALUES(756,'en','dsb','Lower Sorbian');
INSERT INTO "languageNames" VALUES(757,'en','el','Greek');
INSERT INTO "languageNames" VALUES(758,'en','en','English');
INSERT INTO "languageNames" VALUES(759,'en','eo','Esperanto');
INSERT INTO "languageNames" VALUES(760,'en','es','Spanish');
INSERT INTO "languageNames" VALUES(761,'en','et','Estonian');
INSERT INTO "languageNames" VALUES(762,'en','eu','Basque');
INSERT INTO "languageNames" VALUES(763,'en','fa','Persian');
INSERT INTO "languageNames" VALUES(764,'en','fi','Finnish');
INSERT INTO "languageNames" VALUES(765,'en','fo','Faroese');
INSERT INTO "languageNames" VALUES(766,'en','fr','French');
INSERT INTO "languageNames" VALUES(767,'en','fy','Western Frisian');
INSERT INTO "languageNames" VALUES(768,'en','ga','Irish');
INSERT INTO "languageNames" VALUES(769,'en','gd','Scottish Gaelic');
INSERT INTO "languageNames" VALUES(770,'en','gn','Guarani');
INSERT INTO "languageNames" VALUES(771,'en','gv','Manx');
INSERT INTO "languageNames" VALUES(772,'en','he','Hebrew');
INSERT INTO "languageNames" VALUES(773,'en','hi','Hindi');
INSERT INTO "languageNames" VALUES(774,'en','hsb','Upper Sorbian');
INSERT INTO "languageNames" VALUES(775,'en','ht','Haitian');
INSERT INTO "languageNames" VALUES(776,'en','hu','Hungarian');
INSERT INTO "languageNames" VALUES(777,'en','hy','Armenian');
INSERT INTO "languageNames" VALUES(778,'en','ia','Interlingua');
INSERT INTO "languageNames" VALUES(779,'en','id','Indonesian');
INSERT INTO "languageNames" VALUES(780,'en','is','Icelandic');
INSERT INTO "languageNames" VALUES(781,'en','it','Italian');
INSERT INTO "languageNames" VALUES(782,'en','kaa','Karakalpak');
INSERT INTO "languageNames" VALUES(783,'en','kk','Kazakh');
INSERT INTO "languageNames" VALUES(784,'en','ko','Korean');
INSERT INTO "languageNames" VALUES(785,'en','ku','Kurdish');
INSERT INTO "languageNames" VALUES(786,'en','kum','Kumyk');
INSERT INTO "languageNames" VALUES(787,'en','kv','Komi');
INSERT INTO "languageNames" VALUES(789,'en','ky','Kyrgyz');
INSERT INTO "languageNames" VALUES(790,'en','la','Latin');
INSERT INTO "languageNames" VALUES(791,'en','lb','Luxembourgish');
INSERT INTO "languageNames" VALUES(792,'en','lg','Ganda');
INSERT INTO "languageNames" VALUES(793,'en','lo','Lao');
INSERT INTO "languageNames" VALUES(794,'en','lt','Lithuanian');
INSERT INTO "languageNames" VALUES(795,'en','lv','Latvian');
INSERT INTO "languageNames" VALUES(796,'en','mfe','Morisyen');
INSERT INTO "languageNames" VALUES(797,'en','mk','Macedonian');
INSERT INTO "languageNames" VALUES(798,'en','ml','Malayalam');
INSERT INTO "languageNames" VALUES(799,'en','mr','Marathi');
INSERT INTO "languageNames" VALUES(800,'en','mt','Maltese');
INSERT INTO "languageNames" VALUES(801,'en','myv','Erzya');
INSERT INTO "languageNames" VALUES(802,'en','nb','Norwegian Bokmål');
INSERT INTO "languageNames" VALUES(803,'en','ne','Nepali');
INSERT INTO "languageNames" VALUES(804,'en','nl','Dutch');
INSERT INTO "languageNames" VALUES(805,'en','nn','Norwegian Nynorsk');
INSERT INTO "languageNames" VALUES(806,'en','no','Norwegian');
INSERT INTO "languageNames" VALUES(807,'en','nog','Nogai');
INSERT INTO "languageNames" VALUES(808,'en','oc','Occitan');
INSERT INTO "languageNames" VALUES(809,'en','os','Ossetian');
INSERT INTO "languageNames" VALUES(810,'en','pa','Punjabi');
INSERT INTO "languageNames" VALUES(811,'en','pl','Polish');
INSERT INTO "languageNames" VALUES(812,'en','pt','Portuguese');
INSERT INTO "languageNames" VALUES(813,'en','rm','Romansh');
INSERT INTO "languageNames" VALUES(814,'en','rn','Rundi');
INSERT INTO "languageNames" VALUES(815,'en','ro','Romanian');
INSERT INTO "languageNames" VALUES(816,'en','ru','Russian');
INSERT INTO "languageNames" VALUES(817,'en','rup','Aromanian');
INSERT INTO "languageNames" VALUES(818,'en','sa','Sanskrit');
INSERT INTO "languageNames" VALUES(819,'en','sc','Sardinian');
INSERT INTO "languageNames" VALUES(820,'en','sco','Scots');
INSERT INTO "languageNames" VALUES(821,'en','se','Northern Sami');
INSERT INTO "languageNames" VALUES(822,'en','sh','Serbo-Croatian');
INSERT INTO "languageNames" VALUES(823,'en','si','Sinhala');
INSERT INTO "languageNames" VALUES(824,'en','sk','Slovak');
INSERT INTO "languageNames" VALUES(825,'en','sl','Slovenian');
INSERT INTO "languageNames" VALUES(826,'en','sma','Southern Sami');
INSERT INTO "languageNames" VALUES(827,'en','smj','Lule Sami');
INSERT INTO "languageNames" VALUES(828,'en','sq','Albanian');
INSERT INTO "languageNames" VALUES(829,'en','sv','Swedish');
INSERT INTO "languageNames" VALUES(830,'en','sw','Swahili');
INSERT INTO "languageNames" VALUES(831,'en','te','Telugu');
INSERT INTO "languageNames" VALUES(832,'en','tet','Tetum');
INSERT INTO "languageNames" VALUES(833,'en','tg','Tajik');
INSERT INTO "languageNames" VALUES(834,'en','th','Thai');
INSERT INTO "languageNames" VALUES(835,'en','tk','Turkmen');
INSERT INTO "languageNames" VALUES(836,'en','tl','Tagalog');
INSERT INTO "languageNames" VALUES(837,'en','tr','Turkish');
INSERT INTO "languageNames" VALUES(838,'en','tt','Tatar');
INSERT INTO "languageNames" VALUES(839,'en','tyv','Tuvan');
INSERT INTO "languageNames" VALUES(840,'en','udm','Udmurt');
INSERT INTO "languageNames" VALUES(841,'en','uk','Ukrainian');
INSERT INTO "languageNames" VALUES(842,'en','ur','Urdu');
INSERT INTO "languageNames" VALUES(843,'en','uz','Uzbek');
INSERT INTO "languageNames" VALUES(844,'en','vi','Vietnamese');
INSERT INTO "languageNames" VALUES(845,'en','xh','Xhosa');
INSERT INTO "languageNames" VALUES(846,'en','zh','Chinese');
INSERT INTO "languageNames" VALUES(847,'en','zu','Zulu');
INSERT INTO "languageNames" VALUES(848,'tt','kk','казакъча');
INSERT INTO "languageNames" VALUES(849,'tt','tt','татарча');
INSERT INTO "languageNames" VALUES(850,'tt','ky','кыргызча');
INSERT INTO "languageNames" VALUES(851,'tt','tr','төрекчә');
INSERT INTO "languageNames" VALUES(852,'tt','cv','чувашча');
INSERT INTO "languageNames" VALUES(853,'tt','kum','кумыкча');
INSERT INTO "languageNames" VALUES(854,'tt','uz','үзбәкчә');
INSERT INTO "languageNames" VALUES(855,'tt','ba','башкортча');
INSERT INTO "languageNames" VALUES(856,'tt','tk','төрекмәнчә');
INSERT INTO "languageNames" VALUES(857,'tt','kaa','каракалпакча');
INSERT INTO "languageNames" VALUES(858,'tt','tyv','тувача');
INSERT INTO "languageNames" VALUES(859,'tt','az','азәрбайҗанча');
INSERT INTO "languageNames" VALUES(860,'tt','az','урысча');
INSERT INTO "languageNames" VALUES(861,'ba','ba','башҡортса');
COMMIT;

